export const homeObjOne = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Members",
  headLine: "Free access to all Areas and Instruments",
  description:
    "Train with our elite instructors, Fix your dieting and transform your life Forever....So what are you waiting for.",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/workout4.svg").default,
  alt: "exercise",
  dark: true,
  primary: true,
  darkText: false,
};
export const homeObjTwo = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Premium Members",
  headLine: "Free access to all Areas and Instruments",
  description:
    "Train with our elite instructors, Fix your dieting and transform your life Forever....So what are you waiting for.",
  buttonLabel: "Get started",
  imgStart: true,
  img: require("../../images/workout2.svg").default,
  alt: "exercise",
  dark: false,
  primary: false,
  darkText: true,
};
export const homeObjThree = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Premium Members",
  headLine: "Free access to all Areas and Instruments",
  description:
    "Train with our elite instructors, Fix your dieting and transform your life Forever....So what are you waiting for.",
  buttonLabel: "Get started",
  imgStart: false,
  img: require("../../images/workout3.svg").default,
  alt: "exercise",
  dark: false,
  primary: false,
  darkText: true,
};